"""
Training Curve Plots (Task 3)
=============================

Reads the training history and produces the four figures used in the Task 3 analysis,
plus the summary table.

The history is pulled from the published model repository, so the figures can be
regenerated by anyone without access to the original training machine.

Usage
-----
    python plot_training.py                      # fetch from the Hub
    python plot_training.py --csv local.csv      # use a local copy
    python plot_training.py --outdir figures     # where to write the PNGs
"""

import argparse
import csv
import io
import os
import urllib.request

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HUB_CSV = ("https://huggingface.co/hosseinzr/neyshekar-whisper-large-v3-lora"
           "/raw/main/training_curve.csv")

# Evaluation points. These come from trainer_state.json; they are listed explicitly
# so the figures remain reproducible even if only the training curve CSV is available.
EVAL = [
    # step, epoch,  val_loss, WER %, CER %
    (1500, 0.7179, 0.161519, 16.30, 4.77),
    (3000, 1.4355, 0.128770, 12.50, 3.12),
    (4500, 2.1531, 0.100674,  9.57, 2.28),
    (6000, 2.8710, 0.087040,  8.19, 1.94),
    (6270, 3.0000, 0.085669,  8.17, 1.90),
]
FINAL_WER, FINAL_CER = 8.05, 2.00     # full 5,900-sample validation split
STEPS_PER_EPOCH, TOTAL_STEPS = 2089, 6270

BLUE, RED, GREEN, PURPLE, ORANGE, GREY = (
    "#1f77b4", "#d62728", "#2ca02c", "#9467bd", "#ff7f0e", "#999999")


def load(path_or_none):
    if path_or_none:
        with open(path_or_none, encoding="utf-8") as f:
            text = f.read()
    else:
        print(f"[FETCH] {HUB_CSV}")
        text = urllib.request.urlopen(HUB_CSV).read().decode()
    rows = list(csv.DictReader(io.StringIO(text)))
    step = [int(r["step"]) for r in rows]
    loss = [float(r["train_loss"]) for r in rows]
    lr = [float(r["learning_rate"]) for r in rows]
    gn = [float(r["grad_norm"]) if r["grad_norm"] not in ("", "nan") else None for r in rows]
    return step, loss, lr, gn


def smooth(y, w=15):
    return [sum(y[max(0, i - w):i + 1]) / len(y[max(0, i - w):i + 1]) for i in range(len(y))]


def epoch_marks(ax):
    """Dotted vertical lines at the epoch boundaries."""
    for e in (1, 2):
        ax.axvline(STEPS_PER_EPOCH * e, color=GREY, ls=":", lw=1, zorder=0)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--csv", default=None)
    p.add_argument("--outdir", default="figures")
    args = p.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    step, loss, lr, gn = load(args.csv)
    sm = smooth(loss)
    e_step = [e[0] for e in EVAL]
    e_loss = [e[2] for e in EVAL]
    e_wer = [e[3] for e in EVAL]
    e_cer = [e[4] for e in EVAL]

    # --- Figure 1: training vs validation loss ---------------------------------
    fig, ax = plt.subplots(figsize=(9, 4.5))
    ax.plot(step, loss, color=BLUE, lw=0.7, alpha=0.35, label="Training loss (logged every 10 steps)")
    ax.plot(step, sm, color=BLUE, lw=2, label="Training loss (moving average)")
    ax.plot(e_step, e_loss, "o-", color=RED, lw=2, ms=7, label="Validation loss")
    for x, y in zip(e_step, e_loss):
        ax.annotate(f"{y:.4f}", (x, y), textcoords="offset points",
                    xytext=(0, 10), ha="center", fontsize=8, color=RED)
    epoch_marks(ax)
    ax.set_xlabel("Training step")
    ax.set_ylabel("Cross-entropy loss")
    ax.set_title("Training and validation loss")
    ax.legend()
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(f"{args.outdir}/fig1_loss.png", dpi=150)
    plt.close(fig)

    # --- Figure 2: WER and CER -------------------------------------------------
    fig, ax = plt.subplots(figsize=(9, 4.5))
    ax.plot(e_step, e_wer, "o-", color=RED, lw=2, ms=8, label="WER %")
    ax.plot(e_step, e_cer, "s-", color=GREEN, lw=2, ms=8, label="CER %")
    for x, y in zip(e_step, e_wer):
        ax.annotate(f"{y:.2f}", (x, y), textcoords="offset points",
                    xytext=(0, 11), ha="center", fontsize=9, color=RED)
    for x, y in zip(e_step, e_cer):
        ax.annotate(f"{y:.2f}", (x, y), textcoords="offset points",
                    xytext=(0, -17), ha="center", fontsize=9, color=GREEN)
    ax.axhline(FINAL_WER, color=RED, ls="--", lw=1, alpha=0.5)
    ax.annotate(f"final full-set WER {FINAL_WER}", (TOTAL_STEPS, FINAL_WER),
                textcoords="offset points", xytext=(-10, 20), ha="right",
                fontsize=8, color=RED)
    epoch_marks(ax)
    ax.set_xlabel("Training step")
    ax.set_ylabel("Error rate (%)")
    ax.set_title("Word error rate and character error rate")
    ax.legend()
    ax.grid(alpha=0.3)
    ax.set_ylim(0, 18)
    fig.tight_layout()
    fig.savefig(f"{args.outdir}/fig2_wer_cer.png", dpi=150)
    plt.close(fig)

    # --- Figure 3: four-panel overview ----------------------------------------
    fig, axes = plt.subplots(2, 2, figsize=(11, 7))
    for ax, (title, xs, ys, style, colour) in zip(
            axes.ravel(),
            [("Training loss", step, sm, "-", BLUE),
             ("Validation loss", e_step, e_loss, "o-", RED),
             (None, None, None, None, None),
             ("Learning rate", step, lr, "-", PURPLE)]):
        if title is None:
            ax.plot(e_step, e_wer, "o-", color=RED, lw=2, label="WER %")
            ax.plot(e_step, e_cer, "s-", color=GREEN, lw=2, label="CER %")
            ax.set_title("Error rates (%)")
            ax.legend(fontsize=8)
        else:
            ax.plot(xs, ys, style, color=colour, lw=2)
            ax.set_title(title)
        epoch_marks(ax)
        ax.set_xlabel("step")
        ax.grid(alpha=0.3)
    fig.suptitle("Training overview — 3 epochs, 6,270 optimizer steps", fontsize=13)
    fig.tight_layout()
    fig.savefig(f"{args.outdir}/fig3_overview.png", dpi=150)
    plt.close(fig)

    # --- Figure 4: gradient norm (stability evidence) -------------------------
    pts = [(s, g) for s, g in zip(step, gn) if g is not None]
    fig, ax = plt.subplots(figsize=(9, 3.6))
    ax.plot([s for s, _ in pts], [g for _, g in pts], color=ORANGE, lw=0.7, alpha=0.75)
    epoch_marks(ax)
    ax.set_xlabel("Training step")
    ax.set_ylabel("Gradient norm")
    ax.set_title("Gradient norm — bounded throughout, no divergence")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(f"{args.outdir}/fig4_grad_norm.png", dpi=150)
    plt.close(fig)

    # --- numbers for the write-up ---------------------------------------------
    print(f"\n{'=' * 66}\n  TASK 3 SUMMARY TABLE\n{'=' * 66}")
    print(f"{'step':>6}{'epoch':>8}{'train':>10}{'val loss':>11}{'WER %':>9}{'CER %':>8}")
    print("-" * 66)
    for s, ep, vl, w, c in EVAL:
        near = min(range(len(step)), key=lambda i: abs(step[i] - s))
        print(f"{s:>6}{ep:>8.2f}{loss[near]:>10.4f}{vl:>11.4f}{w:>9.2f}{c:>8.2f}")
    print(f"{'final':>6}{3.00:>8.2f}{'':>10}{0.0863:>11.4f}{FINAL_WER:>9.2f}{FINAL_CER:>8.2f}"
          "   <- full 5,900 split")

    print(f"\n{'=' * 66}\n  RELATIVE IMPROVEMENT (first eval -> last eval)\n{'=' * 66}")
    for name, a, b in [("Validation loss", e_loss[0], e_loss[-1]),
                       ("WER", e_wer[0], e_wer[-1]),
                       ("CER", e_cer[0], e_cer[-1])]:
        print(f"  {name:<18} {a:>8.4f} -> {b:>8.4f}   {100 * (a - b) / a:>5.1f}% reduction")

    print(f"\n{'=' * 66}\n  MEAN TRAINING LOSS PER EPOCH\n{'=' * 66}")
    for i in (1, 2, 3):
        lo, hi = STEPS_PER_EPOCH * (i - 1), STEPS_PER_EPOCH * i
        vals = [l for s, l in zip(step, loss) if lo < s <= hi]
        print(f"  epoch {i}: {sum(vals) / len(vals):.4f}   ({len(vals)} logged points)")

    g = [x for x in gn if x is not None]
    print(f"\n{'=' * 66}\n  STABILITY\n{'=' * 66}")
    print(f"  gradient norm  min {min(g):.3f}   max {max(g):.3f}   mean {sum(g) / len(g):.3f}")
    print(f"  NaN gradient norms: {sum(1 for x in gn if x is None)} of {len(gn)} logged steps")
    print(f"  train loss     first {loss[0]:.4f}   last {loss[-1]:.4f}")

    print(f"\nFigures written to {args.outdir}/\n")


if __name__ == "__main__":
    main()
